tdts-udbfw-obj-y += tdts_udbfw_main.o
tdts-udbfw-obj-y += fw_util.o
tdts-udbfw-obj-y += fw_action.o
tdts-udbfw-obj-y += fw_ct_notif.o
tdts-udbfw-obj-y += fw_qos_cmd_nl.o
tdts-udbfw-obj-y += fw_url_query.o
tdts-udbfw-obj-y += fw_meta_extract.o
#;