STRIP=$(CROSS)strip

EXTRACFLAGS := -DBCMWPA2 -fno-delete-null-pointer-checks -mips32 -mtune=mips32

KERNEL_DIR=../../../linux
SHARED_DIR=../../public/shared
CFLAGS	= -I$(KERNEL_DIR)/include -I$(SHARED_DIR) $(EXTRACFLAGS) -Wall -Os
CFLAGS	+= -L../../public/shared -lshared -L../tcapi_lib -ltcapi
CFLAGS  += -Dlinux -DNO_PARALLEL -DPRNINFO

ifneq ($(strip $(TC_CFLAGS)),)
CFLAGS += $(TC_CFLAGS)
endif

OBJS= infosvr.o common.o packet.o storage.o
###OBJS += wlutils.o service.o interface.o
EXECS= infosvr

all: $(EXECS)

.c.o:
	$(CC) -c $(CFLAGS) $<

$(EXECS): $(OBJS)
	$(CC) $(OBJS) -o $@ $(CFLAGS)
	$(STRIP) --strip-unneeded $@

clean:
	rm -f $(EXECS)
