tdts-kmod-obj-y += shell.o
tdts-kmod-obj-y += shell_udb.o
tdts-kmod-obj-y += shell_qos.o
tdts-kmod-obj-y += shell_ct_extra.o
tdts-kmod-obj-y += shell_anomaly.o
tdts-kmod-obj-y += shell_ioctl.o
tdts-kmod-obj-y += shell_procfs.o
tdts-kmod-obj-y += shell_procfs_qos.o
tdts-kmod-obj-y += shell_procfs_ct_extra.o
#;