######################################################################
# Automatically generated by qmake (3.0) ?? 12? 23 21:51:39 2015
######################################################################

TEMPLATE = app
TARGET = dropbox_client
INCLUDEPATH += .

# Input
HEADERS += cJSON.h data.h function.h list.h mem_pool.h
SOURCES += cJSON.c dropbox.c function.c list.c mem_pool.c
