/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef ADSLMIB_H
#define ADSLMIB_H

/*
 * function declarations 
 */
void            init_adslMIB(void);
void            initialize_table_adslAturPhysTable(void);
Netsnmp_Node_Handler adslAturPhysTable_handler;

Netsnmp_First_Data_Point adslAturPhysTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturPhysTable_get_next_data_point;
void            initialize_table_adslLineConfProfileTable(void);
Netsnmp_Node_Handler adslLineConfProfileTable_handler;

Netsnmp_First_Data_Point adslLineConfProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point adslLineConfProfileTable_get_next_data_point;
void            initialize_table_adslAturChanTable(void);
Netsnmp_Node_Handler adslAturChanTable_handler;

Netsnmp_First_Data_Point adslAturChanTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturChanTable_get_next_data_point;
void            initialize_table_adslAtucPerfDataTable(void);
Netsnmp_Node_Handler adslAtucPerfDataTable_handler;

Netsnmp_First_Data_Point adslAtucPerfDataTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucPerfDataTable_get_next_data_point;
void            initialize_table_adslAtucIntervalTable(void);
Netsnmp_Node_Handler adslAtucIntervalTable_handler;

Netsnmp_First_Data_Point adslAtucIntervalTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucIntervalTable_get_next_data_point;
void            initialize_table_adslAturPerfDataTable(void);
Netsnmp_Node_Handler adslAturPerfDataTable_handler;

Netsnmp_First_Data_Point adslAturPerfDataTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturPerfDataTable_get_next_data_point;
void            initialize_table_adslLineAlarmConfProfileTable(void);
Netsnmp_Node_Handler adslLineAlarmConfProfileTable_handler;

Netsnmp_First_Data_Point
    adslLineAlarmConfProfileTable_get_first_data_point;
Netsnmp_Next_Data_Point adslLineAlarmConfProfileTable_get_next_data_point;
void            initialize_table_adslAturChanPerfDataTable(void);
Netsnmp_Node_Handler adslAturChanPerfDataTable_handler;

Netsnmp_First_Data_Point adslAturChanPerfDataTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturChanPerfDataTable_get_next_data_point;
void            initialize_table_adslAturIntervalTable(void);
Netsnmp_Node_Handler adslAturIntervalTable_handler;

Netsnmp_First_Data_Point adslAturIntervalTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturIntervalTable_get_next_data_point;
void            initialize_table_adslAtucPhysTable(void);
Netsnmp_Node_Handler adslAtucPhysTable_handler;

Netsnmp_First_Data_Point adslAtucPhysTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucPhysTable_get_next_data_point;
void            initialize_table_adslAtucChanPerfDataTable(void);
Netsnmp_Node_Handler adslAtucChanPerfDataTable_handler;

Netsnmp_First_Data_Point adslAtucChanPerfDataTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucChanPerfDataTable_get_next_data_point;
void            initialize_table_adslAturChanIntervalTable(void);
Netsnmp_Node_Handler adslAturChanIntervalTable_handler;

Netsnmp_First_Data_Point adslAturChanIntervalTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAturChanIntervalTable_get_next_data_point;
void            initialize_table_adslAtucChanIntervalTable(void);
Netsnmp_Node_Handler adslAtucChanIntervalTable_handler;

Netsnmp_First_Data_Point adslAtucChanIntervalTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucChanIntervalTable_get_next_data_point;
void            initialize_table_adslLineTable(void);
Netsnmp_Node_Handler adslLineTable_handler;

Netsnmp_First_Data_Point adslLineTable_get_first_data_point;
Netsnmp_Next_Data_Point adslLineTable_get_next_data_point;
void            initialize_table_adslAtucChanTable(void);
Netsnmp_Node_Handler adslAtucChanTable_handler;

Netsnmp_First_Data_Point adslAtucChanTable_get_first_data_point;
Netsnmp_Next_Data_Point adslAtucChanTable_get_next_data_point;


void            initialize_table_ctAR5211TxInfoTable(void);
Netsnmp_Node_Handler ctAR5211TxInfoTable_handler;

Netsnmp_First_Data_Point ctAR5211TxInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point ctAR5211TxInfoTable_get_next_data_point;


/*
 * column number definitions for table ctAR5211TxInfoTable 
 */
 /*
#define COLUMN_CTTX15MINES            1
#define COLUMN_CTTX15MINSES            2
#define COLUMN_CTTX15MINUAS            3
#define COLUMN_CTTX1DAYES             4
#define COLUMN_CTTX1DAYSES            5
#define COLUMN_CTTX1DAYUAS            6    */
#define COLUMN_CTTXTOTALES            1
#define COLUMN_CTTXTOTALSES           2
#define COLUMN_CTTXTOTALUAS           3



void            initialize_table_ctAR5211RxInfoTable(void);
Netsnmp_Node_Handler ctAR5211RxInfoTable_handler;

Netsnmp_First_Data_Point ctAR5211RxInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point ctAR5211RxInfoTable_get_next_data_point;


/*
 * column number definitions for table ctAR5211RxInfoTable 
 */
/* 
#define COLUMN_CTRX15MINES            1
#define COLUMN_CTRX15MINSES            2
#define COLUMN_CTRX15MINUAS            3
#define COLUMN_CTRX1DAYES            4
#define COLUMN_CTRX1DAYSES            5
#define COLUMN_CTRX1DAYUAS            6   */
#define COLUMN_CTRXTOTALES            1
#define COLUMN_CTRXTOTALSES           2
#define COLUMN_CTRXTOTALUAS           3


void            initialize_table_ctAR5211BitErrorTable(void);
Netsnmp_Node_Handler ctAR5211BitErrorTable_handler;

Netsnmp_First_Data_Point ctAR5211BitErrorTable_get_first_data_point;
Netsnmp_Next_Data_Point ctAR5211BitErrorTable_get_next_data_point;


/*
 * column number definitions for table ctAR5211BitErrorTable 
 */
#define COLUMN_CTTXBITERROR         1
#define COLUMN_CTRXBITERROR          2


/*
 * column number definitions for table adslAturPhysTable 
 */
#define COLUMN_ADSLATURINVSERIALNUMBER		1
#define COLUMN_ADSLATURINVVENDORID		2
#define COLUMN_ADSLATURINVVERSIONNUMBER		3
#define COLUMN_ADSLATURCURRSNRMGN		4
#define COLUMN_ADSLATURCURRATN		5
#define COLUMN_ADSLATURCURRSTATUS		6
#define COLUMN_ADSLATURCURROUTPUTPWR		7
#define COLUMN_ADSLATURCURRATTAINABLERATE		8

/*
 * column number definitions for table adslLineConfProfileTable 
 */
#define COLUMN_ADSLLINECONFPROFILENAME		1
#define COLUMN_ADSLATUCCONFRATEMODE		2
#define COLUMN_ADSLATUCCONFRATECHANRATIO		3
#define COLUMN_ADSLATUCCONFTARGETSNRMGN		4
#define COLUMN_ADSLATUCCONFMAXSNRMGN		5
#define COLUMN_ADSLATUCCONFMINSNRMGN		6
#define COLUMN_ADSLATUCCONFDOWNSHIFTSNRMGN		7
#define COLUMN_ADSLATUCCONFUPSHIFTSNRMGN		8
#define COLUMN_ADSLATUCCONFMINUPSHIFTTIME		9
#define COLUMN_ADSLATUCCONFMINDOWNSHIFTTIME		10
#define COLUMN_ADSLATUCCHANCONFFASTMINTXRATE		11
#define COLUMN_ADSLATUCCHANCONFINTERLEAVEMINTXRATE		12
#define COLUMN_ADSLATUCCHANCONFFASTMAXTXRATE		13
#define COLUMN_ADSLATUCCHANCONFINTERLEAVEMAXTXRATE		14
#define COLUMN_ADSLATUCCHANCONFMAXINTERLEAVEDELAY		15
#define COLUMN_ADSLATURCONFRATEMODE		16
#define COLUMN_ADSLATURCONFRATECHANRATIO		17
#define COLUMN_ADSLATURCONFTARGETSNRMGN		18
#define COLUMN_ADSLATURCONFMAXSNRMGN		19
#define COLUMN_ADSLATURCONFMINSNRMGN		20
#define COLUMN_ADSLATURCONFDOWNSHIFTSNRMGN		21
#define COLUMN_ADSLATURCONFUPSHIFTSNRMGN		22
#define COLUMN_ADSLATURCONFMINUPSHIFTTIME		23
#define COLUMN_ADSLATURCONFMINDOWNSHIFTTIME		24
#define COLUMN_ADSLATURCHANCONFFASTMINTXRATE		25
#define COLUMN_ADSLATURCHANCONFINTERLEAVEMINTXRATE		26
#define COLUMN_ADSLATURCHANCONFFASTMAXTXRATE		27
#define COLUMN_ADSLATURCHANCONFINTERLEAVEMAXTXRATE		28
#define COLUMN_ADSLATURCHANCONFMAXINTERLEAVEDELAY		29
#define COLUMN_ADSLLINECONFPROFILEROWSTATUS		30

/*
 * column number definitions for table adslAturChanTable 
 */
#define COLUMN_ADSLATURCHANINTERLEAVEDELAY		1
#define COLUMN_ADSLATURCHANCURRTXRATE		2
#define COLUMN_ADSLATURCHANPREVTXRATE		3
#define COLUMN_ADSLATURCHANCRCBLOCKLENGTH		4

/*
 * column number definitions for table adslAtucPerfDataTable 
 */
#define COLUMN_ADSLATUCPERFLOFS		1
#define COLUMN_ADSLATUCPERFLOSS		2
#define COLUMN_ADSLATUCPERFLOLS		3
#define COLUMN_ADSLATUCPERFLPRS		4
#define COLUMN_ADSLATUCPERFESS		5
#define COLUMN_ADSLATUCPERFINITS		6
#define COLUMN_ADSLATUCPERFVALIDINTERVALS		7
#define COLUMN_ADSLATUCPERFINVALIDINTERVALS		8
#define COLUMN_ADSLATUCPERFCURR15MINTIMEELAPSED		9
#define COLUMN_ADSLATUCPERFCURR15MINLOFS		10
#define COLUMN_ADSLATUCPERFCURR15MINLOSS		11
#define COLUMN_ADSLATUCPERFCURR15MINLOLS		12
#define COLUMN_ADSLATUCPERFCURR15MINLPRS		13
#define COLUMN_ADSLATUCPERFCURR15MINESS		14
#define COLUMN_ADSLATUCPERFCURR15MININITS		15
#define COLUMN_ADSLATUCPERFCURR1DAYTIMEELAPSED		16
#define COLUMN_ADSLATUCPERFCURR1DAYLOFS		17
#define COLUMN_ADSLATUCPERFCURR1DAYLOSS		18
#define COLUMN_ADSLATUCPERFCURR1DAYLOLS		19
#define COLUMN_ADSLATUCPERFCURR1DAYLPRS		20
#define COLUMN_ADSLATUCPERFCURR1DAYESS		21
#define COLUMN_ADSLATUCPERFCURR1DAYINITS		22
#define COLUMN_ADSLATUCPERFPREV1DAYMONISECS		23
#define COLUMN_ADSLATUCPERFPREV1DAYLOFS		24
#define COLUMN_ADSLATUCPERFPREV1DAYLOSS		25
#define COLUMN_ADSLATUCPERFPREV1DAYLOLS		26
#define COLUMN_ADSLATUCPERFPREV1DAYLPRS		27
#define COLUMN_ADSLATUCPERFPREV1DAYESS		28
#define COLUMN_ADSLATUCPERFPREV1DAYINITS		29

/*
 * column number definitions for table adslAtucIntervalTable 
 */
#define COLUMN_ADSLATUCINTERVALNUMBER		1
#define COLUMN_ADSLATUCINTERVALLOFS		2
#define COLUMN_ADSLATUCINTERVALLOSS		3
#define COLUMN_ADSLATUCINTERVALLOLS		4
#define COLUMN_ADSLATUCINTERVALLPRS		5
#define COLUMN_ADSLATUCINTERVALESS		6
#define COLUMN_ADSLATUCINTERVALINITS		7
#define COLUMN_ADSLATUCINTERVALVALIDDATA		8

/*
 * column number definitions for table adslAturPerfDataTable 
 */
#define COLUMN_ADSLATURPERFLOFS		1
#define COLUMN_ADSLATURPERFLOSS		2
#define COLUMN_ADSLATURPERFLPRS		3
#define COLUMN_ADSLATURPERFESS		4
#define COLUMN_ADSLATURPERFVALIDINTERVALS		5
#define COLUMN_ADSLATURPERFINVALIDINTERVALS		6
#define COLUMN_ADSLATURPERFCURR15MINTIMEELAPSED		7
#define COLUMN_ADSLATURPERFCURR15MINLOFS		8
#define COLUMN_ADSLATURPERFCURR15MINLOSS		9
#define COLUMN_ADSLATURPERFCURR15MINLPRS		10
#define COLUMN_ADSLATURPERFCURR15MINESS		11
#define COLUMN_ADSLATURPERFCURR1DAYTIMEELAPSED		12
#define COLUMN_ADSLATURPERFCURR1DAYLOFS		13
#define COLUMN_ADSLATURPERFCURR1DAYLOSS		14
#define COLUMN_ADSLATURPERFCURR1DAYLPRS		15
#define COLUMN_ADSLATURPERFCURR1DAYESS		16
#define COLUMN_ADSLATURPERFPREV1DAYMONISECS		17
#define COLUMN_ADSLATURPERFPREV1DAYLOFS		18
#define COLUMN_ADSLATURPERFPREV1DAYLOSS		19
#define COLUMN_ADSLATURPERFPREV1DAYLPRS		20
#define COLUMN_ADSLATURPERFPREV1DAYESS		21

/*
 * column number definitions for table adslLineAlarmConfProfileTable 
 */
#define COLUMN_ADSLLINEALARMCONFPROFILENAME		1
#define COLUMN_ADSLATUCTHRESH15MINLOFS		2
#define COLUMN_ADSLATUCTHRESH15MINLOSS		3
#define COLUMN_ADSLATUCTHRESH15MINLOLS		4
#define COLUMN_ADSLATUCTHRESH15MINLPRS		5
#define COLUMN_ADSLATUCTHRESH15MINESS		6
#define COLUMN_ADSLATUCTHRESHFASTRATEUP		7
#define COLUMN_ADSLATUCTHRESHINTERLEAVERATEUP		8
#define COLUMN_ADSLATUCTHRESHFASTRATEDOWN		9
#define COLUMN_ADSLATUCTHRESHINTERLEAVERATEDOWN		10
#define COLUMN_ADSLATUCINITFAILURETRAPENABLE		11
#define COLUMN_ADSLATURTHRESH15MINLOFS		12
#define COLUMN_ADSLATURTHRESH15MINLOSS		13
#define COLUMN_ADSLATURTHRESH15MINLPRS		14
#define COLUMN_ADSLATURTHRESH15MINESS		15
#define COLUMN_ADSLATURTHRESHFASTRATEUP		16
#define COLUMN_ADSLATURTHRESHINTERLEAVERATEUP		17
#define COLUMN_ADSLATURTHRESHFASTRATEDOWN		18
#define COLUMN_ADSLATURTHRESHINTERLEAVERATEDOWN		19
#define COLUMN_ADSLLINEALARMCONFPROFILEROWSTATUS		20

/*
 * column number definitions for table adslAturChanPerfDataTable 
 */
#define COLUMN_ADSLATURCHANRECEIVEDBLKS		1
#define COLUMN_ADSLATURCHANTRANSMITTEDBLKS		2
#define COLUMN_ADSLATURCHANCORRECTEDBLKS		3
#define COLUMN_ADSLATURCHANUNCORRECTBLKS		4
#define COLUMN_ADSLATURCHANPERFVALIDINTERVALS		5
#define COLUMN_ADSLATURCHANPERFINVALIDINTERVALS		6
#define COLUMN_ADSLATURCHANPERFCURR15MINTIMEELAPSED		7
#define COLUMN_ADSLATURCHANPERFCURR15MINRECEIVEDBLKS		8
#define COLUMN_ADSLATURCHANPERFCURR15MINTRANSMITTEDBLKS		9
#define COLUMN_ADSLATURCHANPERFCURR15MINCORRECTEDBLKS		10
#define COLUMN_ADSLATURCHANPERFCURR15MINUNCORRECTBLKS		11
#define COLUMN_ADSLATURCHANPERFCURR1DAYTIMEELAPSED		12
#define COLUMN_ADSLATURCHANPERFCURR1DAYRECEIVEDBLKS		13
#define COLUMN_ADSLATURCHANPERFCURR1DAYTRANSMITTEDBLKS		14
#define COLUMN_ADSLATURCHANPERFCURR1DAYCORRECTEDBLKS		15
#define COLUMN_ADSLATURCHANPERFCURR1DAYUNCORRECTBLKS		16
#define COLUMN_ADSLATURCHANPERFPREV1DAYMONISECS		17
#define COLUMN_ADSLATURCHANPERFPREV1DAYRECEIVEDBLKS		18
#define COLUMN_ADSLATURCHANPERFPREV1DAYTRANSMITTEDBLKS		19
#define COLUMN_ADSLATURCHANPERFPREV1DAYCORRECTEDBLKS		20
#define COLUMN_ADSLATURCHANPERFPREV1DAYUNCORRECTBLKS		21

/*
 * column number definitions for table adslAturIntervalTable 
 */
#define COLUMN_ADSLATURINTERVALNUMBER		1
#define COLUMN_ADSLATURINTERVALLOFS		2
#define COLUMN_ADSLATURINTERVALLOSS		3
#define COLUMN_ADSLATURINTERVALLPRS		4
#define COLUMN_ADSLATURINTERVALESS		5
#define COLUMN_ADSLATURINTERVALVALIDDATA		6

/*
 * column number definitions for table adslAtucPhysTable 
 */
#define COLUMN_ADSLATUCINVSERIALNUMBER		1
#define COLUMN_ADSLATUCINVVENDORID		2
#define COLUMN_ADSLATUCINVVERSIONNUMBER		3
#define COLUMN_ADSLATUCCURRSNRMGN		4
#define COLUMN_ADSLATUCCURRATN		5
#define COLUMN_ADSLATUCCURRSTATUS		6
#define COLUMN_ADSLATUCCURROUTPUTPWR		7
#define COLUMN_ADSLATUCCURRATTAINABLERATE		8

/*
 * column number definitions for table adslAtucChanPerfDataTable 
 */
#define COLUMN_ADSLATUCCHANRECEIVEDBLKS		1
#define COLUMN_ADSLATUCCHANTRANSMITTEDBLKS		2
#define COLUMN_ADSLATUCCHANCORRECTEDBLKS		3
#define COLUMN_ADSLATUCCHANUNCORRECTBLKS		4
#define COLUMN_ADSLATUCCHANPERFVALIDINTERVALS		5
#define COLUMN_ADSLATUCCHANPERFINVALIDINTERVALS		6
#define COLUMN_ADSLATUCCHANPERFCURR15MINTIMEELAPSED		7
#define COLUMN_ADSLATUCCHANPERFCURR15MINRECEIVEDBLKS		8
#define COLUMN_ADSLATUCCHANPERFCURR15MINTRANSMITTEDBLKS		9
#define COLUMN_ADSLATUCCHANPERFCURR15MINCORRECTEDBLKS		10
#define COLUMN_ADSLATUCCHANPERFCURR15MINUNCORRECTBLKS		11
#define COLUMN_ADSLATUCCHANPERFCURR1DAYTIMEELAPSED		12
#define COLUMN_ADSLATUCCHANPERFCURR1DAYRECEIVEDBLKS		13
#define COLUMN_ADSLATUCCHANPERFCURR1DAYTRANSMITTEDBLKS		14
#define COLUMN_ADSLATUCCHANPERFCURR1DAYCORRECTEDBLKS		15
#define COLUMN_ADSLATUCCHANPERFCURR1DAYUNCORRECTBLKS		16
#define COLUMN_ADSLATUCCHANPERFPREV1DAYMONISECS		17
#define COLUMN_ADSLATUCCHANPERFPREV1DAYRECEIVEDBLKS		18
#define COLUMN_ADSLATUCCHANPERFPREV1DAYTRANSMITTEDBLKS		19
#define COLUMN_ADSLATUCCHANPERFPREV1DAYCORRECTEDBLKS		20
#define COLUMN_ADSLATUCCHANPERFPREV1DAYUNCORRECTBLKS		21

/*
 * column number definitions for table adslAturChanIntervalTable 
 */
#define COLUMN_ADSLATURCHANINTERVALNUMBER		1
#define COLUMN_ADSLATURCHANINTERVALRECEIVEDBLKS		2
#define COLUMN_ADSLATURCHANINTERVALTRANSMITTEDBLKS		3
#define COLUMN_ADSLATURCHANINTERVALCORRECTEDBLKS		4
#define COLUMN_ADSLATURCHANINTERVALUNCORRECTBLKS		5
#define COLUMN_ADSLATURCHANINTERVALVALIDDATA		6

/*
 * column number definitions for table adslAtucChanIntervalTable 
 */
#define COLUMN_ADSLATUCCHANINTERVALNUMBER		1
#define COLUMN_ADSLATUCCHANINTERVALRECEIVEDBLKS		2
#define COLUMN_ADSLATUCCHANINTERVALTRANSMITTEDBLKS		3
#define COLUMN_ADSLATUCCHANINTERVALCORRECTEDBLKS		4
#define COLUMN_ADSLATUCCHANINTERVALUNCORRECTBLKS		5
#define COLUMN_ADSLATUCCHANINTERVALVALIDDATA		6

/*
 * column number definitions for table adslLineTable 
 */
#define COLUMN_ADSLLINECODING		1
#define COLUMN_ADSLLINETYPE		2
#define COLUMN_ADSLLINESPECIFIC		3
#define COLUMN_ADSLLINECONFPROFILE		4
#define COLUMN_ADSLLINEALARMCONFPROFILE		5

/*
 * column number definitions for table adslAtucChanTable 
 */
#define COLUMN_ADSLATUCCHANINTERLEAVEDELAY		1
#define COLUMN_ADSLATUCCHANCURRTXRATE		2
#define COLUMN_ADSLATUCCHANPREVTXRATE		3
#define COLUMN_ADSLATUCCHANCRCBLOCKLENGTH		4
#endif                          /* ADSLMIB_H */
