tdts-kmod-obj-y += shell.o
tdts-kmod-obj-y += shell_ioctl.o
tdts-kmod-obj-y += shell_ioctl_dbg.o
tdts-kmod-obj-y += shell_ioctl_sig.o
tdts-kmod-obj-y += shell_ioctl_stat.o
tdts-kmod-obj-y += shell_atimer.o
tdts-kmod-obj-y += shell_deprecated_procfs.o

#;
