/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("atmMIB")) init_atmMIB();
  if (should_init("snmp_mib")) init_snmp_mib();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("at")) init_at();
  if (should_init("ip")) init_ip();
  if (should_init("tcp")) init_tcp();
  if (should_init("icmp")) init_icmp();
  if (should_init("udp")) init_udp();
  if (should_init("vacm_context")) init_vacm_context();
  if (should_init("var_route")) init_var_route();
  if (should_init("tcpTable")) init_tcpTable();
  if (should_init("udpTable")) init_udpTable();
  if (should_init("ifTable")) init_ifTable();
  if (should_init("interface")) init_interface();
  if (should_init("adsl_mib")) init_adsl_mib(); 
