# This makefile snippet is generated by the pimd configure script.

# Initial definitions ...
# -D_GNU_SOURCE Use GNU extensions, where possible
# -D_BSD_SOURCE Use functions derived from 4.3 BSD Unix rather than POSIX.1
#               In GLIBC >= v2.20 this is replaced with -D_DEFAULT_SOURCE  
# -DPIM         Enable PIM extensions in RSRR
DEFS          = -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_GNU_SOURCE -DPIM
# EXTRA_OBJS  = For locally provided objects missing on some platforms, e.g., strlcpy.o
# EXTRA_LIBS  = For platform specific libraries, e.g., -lutil

# Linux specific settings ...
INCLUDES     = -Iinclude
DEFS        += -DRAW_OUTPUT_IS_RAW -DIOCTL_OK_ON_RAW_SOCKET
ROUTER_OBJS += netlink.o
EXTRA_OBJS  += libite/pidfile.o libite/strtonum.o
EXTRA_LIBS   =

# Build specific settings ...
CFLAGS      += -O2

# Configured settings/features ...
prefix        = /usr
sysconfdir   += /usr/etc
sysconfdir    = /etc
DEFS         += -DPACKAGE_BUGREPORT=\"https://github.com/troglobit/pimd/issues\"
DEFS         += -DENABLE_PIM_HELLO_GENID
