# $Id: //BBN_Linux/Branch/Branch_for_SDK_Release_MultiChip_20111013/tclinux_phoenix/linux/arch/sparc64/prom/Makefile#1 $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o misc.o \
	   tree.o console.o printf.o p1275.o cif.o
