#
# Automatically generated make config: don't edit
# Wed Jan 11 11:04:16 2012
#
# TCSUPPORT_CPU_TC3162 is not set
# TCSUPPORT_CPU_TC3162U is not set
# TCSUPPORT_CPU_RT63260 is not set
# TCSUPPORT_CPU_TC3262 is not set
# TCSUPPORT_CPU_TC3182 is not set
# TCSUPPORT_CPU_RT63165 is not set
# TCSUPPORT_CPU_RT63365 is not set
TCSUPPORT_CPU_RT63368=y
# TCSUPPORT_CPU_RT65168 is not set
WAN_ATM=y
WAN_ETHER=y

#
# WAN Transfer Mode Support
#

#
# At Least One of The Following Has to Be Chosen!
#
TCSUPPORT_WAN_ATM=y
TCSUPPORT_WAN_ETHER=y
# TCSUPPORT_SDRAM_8M is not set
# TCSUPPORT_SDRAM_16M is not set
TCSUPPORT_SDRAM_32M=y
# TCSUPPORT_SDRAM_64M is not set
TCSUPPORT_BOOT_LZMA=y
# TCSUPPORT_BB_SPI is not set
TCSUPPORT_BB_NAND=y
# TCSUPPORT_KERNELCONFIG_AUTO is not set
# TCSUPPORT_KERNELCONFIG_TC3162 is not set
# TCSUPPORT_KERNELCONFIG_TC3162_PB is not set
# TCSUPPORT_KERNELCONFIG_TC3162_VOIP is not set
# TCSUPPORT_KERNELCONFIG_TC3162_IPv6 is not set
# TCSUPPORT_KERNELCONFIG_TC3162U is not set
# TCSUPPORT_KERNELCONFIG_TC3162U_IPv6 is not set
# TCSUPPORT_KERNELCONFIG_TC3262 is not set
# TCSUPPORT_KERNELCONFIG_TC3182 is not set
# TCSUPPORT_KERNELCONFIG_RT63165 is not set
TCSUPPORT_KERNELCONFIG_RT63365=y
# TCSUPPORT_KERNELCONFIG_RT65168 is not set
# TCSUPPORT_BUSYBOXCONFIG_AUTO is not set
# TCSUPPORT_BUSYBOXCONFIG_TC3162 is not set
# TCSUPPORT_BUSYBOXCONFIG_TC3162_PB is not set
# TCSUPPORT_BUSYBOXCONFIG_TC3162_IPv6 is not set
# TCSUPPORT_BUSYBOXCONFIG_TC3162U is not set
# TCSUPPORT_BUSYBOXCONFIG_TC3162U_IPv6 is not set
TCSUPPORT_BUSYBOXCONFIG_TC3262=y

#
# Driver Feature
#
# TCSUPPORT_DMT_3085 is not set
# TCSUPPORT_DMT_3086 is not set
TCSUPPORT_DMT_3087=y
# TCSUPPORT_DMT_3095 is not set
# TCSUPPORT_DUAL_IMAGE is not set
TCSUPPORT_TR68LED=y
# TCSUPPORT_LEDKEY is not set
TCSUPPORT_WLAN=y
TCSUPPORT_WLAN_8021X=y
TCSUPPORT_WLAN_8021X_EXT=y
TCSUPPORT_WLAN_8021X_EXT_SHOW_MAC=y
TCSUPPORT_WLAN_WPS=y
TCSUPPORT_WLAN_WDS=y
TCSUPPORT_WLAN_IGMPSNOOP=y
TCSUPPORT_WLAN_ATE=y
TCSUPPORT_WLAN_QATOOL=y
TCSUPPORT_WLAN_WPS_LEDSPEC=y
TCSUPPORT_WLAN_GPIO=y
# TCSUPPORT_WLAN_RT2561 is not set
# TCSUPPORT_WLAN_RT3390 is not set
TCSUPPORT_WLAN_RT5392=y
# TCSUPPORT_WLAN_RT5390 is not set
# TCSUPPORT_WLAN_RT3090 is not set
TCSUPPORT_NODUAL_BAND=y
# TCSUPPORT_DUAL_WLAN_RT5592  is not set
TCSUPPORT_USBHOST=y
TCSUPPORT_USB_NTFS=y
TCSUPPORT_USB_AUTOMOUNT=y
TCSUPPORT_USB_PRINTER_SERVER=y
TCSUPPORT_USB_3G_DONGLE=y
TCSUPPORT_USB_CAMERA=y
TCSUPPORT_CMDAPI=y
# TCSUPPORT_AUTOBENCH is not set
TCSUPPORT_NAND_FLASH=y
TCSUPPORT_RA_HWNAT=y

#
# Common Feature
#
TCSUPPORT_IPV6=y
TCSUPPORT_IPV6_ENHANCEMENT=y
TCSUPPORT_DSLITE=y
TCSUPPORT_6RD=y
TCSUPPORT_OPT212=y
TCSUPPORT_IPV6_ADVANCE=y
TCSUPPORT_IPV6_FIREWALL=y
TCSUPPORT_IPV6_FIREWALL_RFC2827=y
# TCSUPPORT_IPV6_RIPNG is not set
TCSUPPORT_IPV6_TELNET=y
TCSUPPORT_IPV6_TFTP=y
TCSUPPORT_IPV6_FTP=y
TCSUPPORT_IPV6_INETD=y
# TCSUPPORT_IPV6_PRIVACYADDRS is not set
TCSUPPORT_VOIP=y
# TCSUPPORT_VOIP_WITH_DSP_AC is not set
# TCSUPPORT_VOIP_WITH_DSP_D2 is not set
# TCSUPPORT_VOIP_WITH_DSP_D2_2S1O is not set
# TCSUPPORT_VOIP_WITH_DSP_D2_2S1O_SILAB is not set
# TCSUPPORT_VOIP_WITH_DSP_EVA_2S1O is not set
TCSUPPORT_VOIP_WITH_DSP_EVA_1S_89156=y
TCSUPPORT_CWMP=y
TCSUPPORT_CWMP_CRPORTCHANGE=y
TCSUPPORT_CWMP_PRECISE_TIME=y
# TCSUPPORT_CWMP_CS_BSNL is not set
TCSUPPORT_RANDOM_INFORM=y
# TCSUPPORT_TRACEROUTE is not set
TCSUPPORT_DOWNSTREAM_QOS=y
TCSUPPORT_QOS=y
# TCSUPPORT_QOS_QUEUE_MODIFY is not set
TCSUPPORT_PORTBIND=y
TCSUPPORT_VLAN_TAG=y
# TCSUPPORT_VTAG_ALLDEV is not set
TCSUPPORT_WEBSERVER_SSL=y
TCSUPPORT_SSH=y
TCSUPPORT_SNMP=y
TCSUPPORT_SNMP_FULL=y
TCSUPPORT_START_TRAP=y
TCSUPPORT_SNMP_V3=y
TCSUPPORT_IPV6_SNMP=y
# TCSUPPORT_SNMP_REDUCED is not set
TCSUPPORT_SNMP_TRUSTIP=y
TCSUPPORT_SNMP_ATMADSL=y
TCSUPPORT_ALIASIP=y
TCSUPPORT_DHCP_STATIC=y
TCSUPPORT_DHCP_PROFILE=y
# TCSUPPORT_E8B is not set
# TCSUPPORT_DNSEACHPVC is not set
TCSUPPORT_MLD_SNOOPING=y
TCSUPPORT_MLD_PROXY=y
TCSUPPORT_IGMP_PROXY_V3=y
TCSUPPORT_IGMP_SNOOPING=y
TCSUPPORT_SMUX=y
TCSUPPORT_MTD_ENCHANCEMENT=y
TCSUPPORT_RESERVEAREA_BLOCK=4
TCSUPPORT_BACKUPROMFILE=y
# TCSUPPORT_NOTDEFAULTROMFILEAREA is not set
# TCSUPPORT_CT_2PWIFI is not set
TCSUPPORT_PRODUCTIONLINE=y
# TCSUPPORT_UNIQUEMAC is not set
TCSUPPORT_SYSLOG=y
TCSUPPORT_SYSLOG_ENHANCE=y
TCSUPPORT_REMOTE_SYSLOG=y
# TCSUPPORT_AUTO_IP is not set
TCSUPPORT_DMS=y
TCSUPPORT_DMS_FULL_FORMAT=y
TCSUPPORT_BRIDGE_FASTPATH=y
RA_PARENTALCONTROL=y
TCSUPPORT_PARENTAL_URLBLOCK=y
# TCSUPPORT_AUTO_DEFAULT_ROUTER is not set
TCSUPPORT_SIPROXD=y
#TCSUPPORT_SAMBA is not set
# TCSUPPORT_CODE_SHRINK is not set
# TCSUPPORT_MNT_CONF is not set
RA_ETHERMEDIATYPE=y
TCSUPPORT_MODEL_CHECK=y
TCSUPPORT_PORT_TRIGGER=y
TCSUPPORT_RA_GUI=y
TCSUPPORT_FILTER_DSCP=y
# TCSUPPORT_2PORTS is not set
TCSUPPORT_DHCP_PORT_FLT=y
TCSUPPORT_1NTP_SERVER=y
# TCSUPPORT_2NTP_SERVER is not set
# TCSUPPORT_3NTP_SERVER is not set
TCSUPPORT_PPP_AUTHEN=y
TCSUPPORT_TFTP_UPGRADE_PROTECT=y
TCSUPPORT_TR069_OPT43=y
TCSUPPORT_GENERAL_MULTILANGUAGE=y
# TCSUPPORT_FWNAME_NOCHK is not set
TCSUPPORT_MODEL_NAME_CUSKIT=y
# TCSUPPORT_MEMORY_CONTROL is not set
# TCSUPPORT_SBTHROUGHPUT_ENHANCE is not set
TCSUPPORT_VPN_SWITCH_GUI=y
TCSUPPORT_LAYER3FORWARD_ENHANCEMENT=y
# TCSUPPORT_UPGRADE_WDOGREBOOT is not set
# TCSUPPORT_LED_BTN_CHECK is not set
# TCSUPPORT_RESTORE_LINOS_INFO is not set
TCSUPPORT_WPA_SUPPLICANT=y
TCSUPPORT_SUPPORT_FLASH=y
TCSUPPORT_TEST_LED_ALL=y
# TCSUPPORT_RESTORE_ROM_T is not set
TCSUPPORT_WLAN_MAXSTANUM_GUI=y
TCSUPPORT_MULTISERVICE_ON_WAN=y
TCSUPPORT_RELEASED_CODE=y
#
# Ethernet Port Mapping to Switch Port
#
# TCSUPPORT_MANUAL_ETHERNET_PORTMAP is not set
