/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.2
 */
#ifndef ATMMIB_H
#define ATMMIB_H

void init_atmMIB(void);
void initialize_table_aal5VccTable(void);
Netsnmp_Node_Handler aal5VccTable_handler;
Netsnmp_First_Data_Point aal5VccTable_get_first_data_point;
Netsnmp_Next_Data_Point    aal5VccTable_get_next_data_point;

void initialize_table_atmInterfaceDs3PlcpTable(void);
Netsnmp_Node_Handler atmInterfaceDs3PlcpTable_handler;
Netsnmp_First_Data_Point  atmInterfaceDs3PlcpTable_get_first_data_point;
Netsnmp_Next_Data_Point   atmInterfaceDs3PlcpTable_get_next_data_point;

void initialize_table_atmVclTable(void);
Netsnmp_Node_Handler atmVclTable_handler;
Netsnmp_First_Data_Point   atmVclTable_get_first_data_point;
Netsnmp_Next_Data_Point    atmVclTable_get_next_data_point;

void initialize_table_atmVcCrossConnectTable(void);
Netsnmp_Node_Handler atmVcCrossConnectTable_handler;
Netsnmp_First_Data_Point  atmVcCrossConnectTable_get_first_data_point;
Netsnmp_Next_Data_Point   atmVcCrossConnectTable_get_next_data_point;

void initialize_table_atmTrafficDescrParamTable(void);
Netsnmp_Node_Handler atmTrafficDescrParamTable_handler;
Netsnmp_First_Data_Point   atmTrafficDescrParamTable_get_first_data_point;
Netsnmp_Next_Data_Point    atmTrafficDescrParamTable_get_next_data_point;

void initialize_table_atmVplTable(void);
Netsnmp_Node_Handler atmVplTable_handler;
Netsnmp_First_Data_Point  atmVplTable_get_first_data_point;
Netsnmp_Next_Data_Point   atmVplTable_get_next_data_point;

void initialize_table_atmInterfaceTCTable(void);
Netsnmp_Node_Handler atmInterfaceTCTable_handler;
Netsnmp_First_Data_Point   atmInterfaceTCTable_get_first_data_point;
Netsnmp_Next_Data_Point    atmInterfaceTCTable_get_next_data_point;

void initialize_table_atmVpCrossConnectTable(void);
Netsnmp_Node_Handler atmVpCrossConnectTable_handler;
Netsnmp_First_Data_Point  atmVpCrossConnectTable_get_first_data_point;
Netsnmp_Next_Data_Point   atmVpCrossConnectTable_get_next_data_point;

void initialize_table_atmInterfaceConfTable(void);
Netsnmp_Node_Handler atmInterfaceConfTable_handler;
Netsnmp_First_Data_Point   atmInterfaceConfTable_get_first_data_point;
Netsnmp_Next_Data_Point    atmInterfaceConfTable_get_next_data_point;



/* column number definitions for table aal5VccTable */
       #define COLUMN_AAL5VCCVPI		1
       #define COLUMN_AAL5VCCVCI		2
       #define COLUMN_AAL5VCCCRCERRORS		3
       #define COLUMN_AAL5VCCSARTIMEOUTS		4
       #define COLUMN_AAL5VCCOVERSIZEDSDUS		5

/* column number definitions for table atmInterfaceDs3PlcpTable */
       #define COLUMN_ATMINTERFACEDS3PLCPSEFSS		1
       #define COLUMN_ATMINTERFACEDS3PLCPALARMSTATE		2
       #define COLUMN_ATMINTERFACEDS3PLCPUASS		3

/* column number definitions for table atmVclTable */
       #define COLUMN_ATMVCLVPI		1
       #define COLUMN_ATMVCLVCI		2
       #define COLUMN_ATMVCLADMINSTATUS		3
       #define COLUMN_ATMVCLOPERSTATUS		4
       #define COLUMN_ATMVCLLASTCHANGE		5
       #define COLUMN_ATMVCLRECEIVETRAFFICDESCRINDEX		6
       #define COLUMN_ATMVCLTRANSMITTRAFFICDESCRINDEX		7
       #define COLUMN_ATMVCCAALTYPE		8
       #define COLUMN_ATMVCCAAL5CPCSTRANSMITSDUSIZE		9
       #define COLUMN_ATMVCCAAL5CPCSRECEIVESDUSIZE		10
       #define COLUMN_ATMVCCAAL5ENCAPSTYPE		11
       #define COLUMN_ATMVCLCROSSCONNECTIDENTIFIER		12
       #define COLUMN_ATMVCLROWSTATUS		13
       #define COLUMN_ATMVCLCASTTYPE		14
       #define COLUMN_ATMVCLCONNKIND		15

/* column number definitions for table atmVcCrossConnectTable */
       #define COLUMN_ATMVCCROSSCONNECTINDEX		1
       #define COLUMN_ATMVCCROSSCONNECTLOWIFINDEX		2
       #define COLUMN_ATMVCCROSSCONNECTLOWVPI		3
       #define COLUMN_ATMVCCROSSCONNECTLOWVCI		4
       #define COLUMN_ATMVCCROSSCONNECTHIGHIFINDEX		5
       #define COLUMN_ATMVCCROSSCONNECTHIGHVPI		6
       #define COLUMN_ATMVCCROSSCONNECTHIGHVCI		7
       #define COLUMN_ATMVCCROSSCONNECTADMINSTATUS		8
       #define COLUMN_ATMVCCROSSCONNECTL2HOPERSTATUS		9
       #define COLUMN_ATMVCCROSSCONNECTH2LOPERSTATUS		10
       #define COLUMN_ATMVCCROSSCONNECTL2HLASTCHANGE		11
       #define COLUMN_ATMVCCROSSCONNECTH2LLASTCHANGE		12
       #define COLUMN_ATMVCCROSSCONNECTROWSTATUS		13

/* column number definitions for table atmTrafficDescrParamTable */
       #define COLUMN_ATMTRAFFICDESCRPARAMINDEX		1
       #define COLUMN_ATMTRAFFICDESCRTYPE		2
       #define COLUMN_ATMTRAFFICDESCRPARAM1		3
       #define COLUMN_ATMTRAFFICDESCRPARAM2		4
       #define COLUMN_ATMTRAFFICDESCRPARAM3		5
       #define COLUMN_ATMTRAFFICDESCRPARAM4		6
       #define COLUMN_ATMTRAFFICDESCRPARAM5		7
       #define COLUMN_ATMTRAFFICQOSCLASS		8
       #define COLUMN_ATMTRAFFICDESCRROWSTATUS		9
       #define COLUMN_ATMSERVICECATEGORY		10
       #define COLUMN_ATMTRAFFICFRAMEDISCARD		11

/* column number definitions for table atmVplTable */
       #define COLUMN_ATMVPLVPI		1
       #define COLUMN_ATMVPLADMINSTATUS		2
       #define COLUMN_ATMVPLOPERSTATUS		3
       #define COLUMN_ATMVPLLASTCHANGE		4
       #define COLUMN_ATMVPLRECEIVETRAFFICDESCRINDEX		5
       #define COLUMN_ATMVPLTRANSMITTRAFFICDESCRINDEX		6
       #define COLUMN_ATMVPLCROSSCONNECTIDENTIFIER		7
       #define COLUMN_ATMVPLROWSTATUS		8
       #define COLUMN_ATMVPLCASTTYPE		9
       #define COLUMN_ATMVPLCONNKIND		10

/* column number definitions for table atmInterfaceTCTable */
       #define COLUMN_ATMINTERFACEOCDEVENTS		1
       #define COLUMN_ATMINTERFACETCALARMSTATE		2

/* column number definitions for table atmVpCrossConnectTable */
       #define COLUMN_ATMVPCROSSCONNECTINDEX		1
       #define COLUMN_ATMVPCROSSCONNECTLOWIFINDEX		2
       #define COLUMN_ATMVPCROSSCONNECTLOWVPI		3
       #define COLUMN_ATMVPCROSSCONNECTHIGHIFINDEX		4
       #define COLUMN_ATMVPCROSSCONNECTHIGHVPI		5
       #define COLUMN_ATMVPCROSSCONNECTADMINSTATUS		6
       #define COLUMN_ATMVPCROSSCONNECTL2HOPERSTATUS		7
       #define COLUMN_ATMVPCROSSCONNECTH2LOPERSTATUS		8
       #define COLUMN_ATMVPCROSSCONNECTL2HLASTCHANGE		9
       #define COLUMN_ATMVPCROSSCONNECTH2LLASTCHANGE		10
       #define COLUMN_ATMVPCROSSCONNECTROWSTATUS		11

/* column number definitions for table atmInterfaceConfTable */
       #define COLUMN_ATMINTERFACEMAXVPCS		1
       #define COLUMN_ATMINTERFACEMAXVCCS		2
       #define COLUMN_ATMINTERFACECONFVPCS		3
       #define COLUMN_ATMINTERFACECONFVCCS		4
       #define COLUMN_ATMINTERFACEMAXACTIVEVPIBITS		5
       #define COLUMN_ATMINTERFACEMAXACTIVEVCIBITS		6
       #define COLUMN_ATMINTERFACEILMIVPI		7
       #define COLUMN_ATMINTERFACEILMIVCI		8
       #define COLUMN_ATMINTERFACEADDRESSTYPE		9
       #define COLUMN_ATMINTERFACEADMINADDRESS		10
       #define COLUMN_ATMINTERFACEMYNEIGHBORIPADDRESS		11
       #define COLUMN_ATMINTERFACEMYNEIGHBORIFNAME		12
       #define COLUMN_ATMINTERFACECURRENTMAXVPIBITS		13
       #define COLUMN_ATMINTERFACECURRENTMAXVCIBITS		14
       #define COLUMN_ATMINTERFACESUBSCRADDRESS		15
#endif /* ATMMIB_H */
