######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 3 11:44:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += base.h list.h
SOURCES += base.c list.c webdav.c
